### ISSUE TITLE
Unable to add tasks

### ISSUE THREAD

**Issue by findkiko** [untitaker/taskrs#23]
Trying out this app I'm unable to add tasks. Seeing the following console error:

```
all.js:51173 Uncaught TypeError: Cannot read property 'setState' of null
    at startAdd (https://taskrs.5apps.com/js/all.js:51173:21)
    at Object.ReactErrorUtils.invokeGuardedCallback (https://taskrs.5apps.com/js/all.js:9982:16)
    at executeDispatch (https://taskrs.5apps.com/js/all.js:9506:21)
    at Object.executeDispatchesInOrder (https://taskrs.5apps.com/js/all.js:9529:5)
    at executeDispatchesAndRelease (https://taskrs.5apps.com/js/all.js:7429:22)
    at executeDispatchesAndReleaseTopLevel (https://taskrs.5apps.com/js/all.js:7440:10)
    at Array.forEach (native)
    at forEachAccumulated (https://taskrs.5apps.com/js/all.js:24274:9)
    at Object.processEventQueue (https://taskrs.5apps.com/js/all.js:7643:7)
    at runEventQueueInBatch (https://taskrs.5apps.com/js/all.js:61039:18)
```
The error fires when typing in the input field.
Though it is loading and syncing existing tasks from a previous try-out. Any ideas?

Edit: The source is loaded from 5apps.com site if that makes any difference.

**Comment by untitaker** [comment]
Sorry, taskrs is currently unmaintained.

On 13 May 2017 02:37:12 GMT+02:00, Kiko Marrs <notifications@github.com> wrote:
>Trying out this app I'm unable to add tasks. Seeing the following
>console error:
>
>```
>all.js:51173 Uncaught TypeError: Cannot read property 'setState' of
>null
>    at startAdd (https://taskrs.5apps.com/js/all.js:51173:21)
>at Object.ReactErrorUtils.invokeGuardedCallback
>(https://taskrs.5apps.com/js/all.js:9982:16)
>    at executeDispatch (https://taskrs.5apps.com/js/all.js:9506:21)
>at Object.executeDispatchesInOrder
>(https://taskrs.5apps.com/js/all.js:9529:5)
>at executeDispatchesAndRelease
>(https://taskrs.5apps.com/js/all.js:7429:22)
>at executeDispatchesAndReleaseTopLevel
>(https://taskrs.5apps.com/js/all.js:7440:10)
>    at Array.forEach (native)
>    at forEachAccumulated (https://taskrs.5apps.com/js/all.js:24274:9)
>at Object.processEventQueue (https://taskrs.5apps.com/js/all.js:7643:7)
>  at runEventQueueInBatch (https://taskrs.5apps.com/js/all.js:61039:18)
>```
>The error fires when typing in the input field.
>Though it is loading and syncing existing tasks from a previous
>try-out. Any ideas?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/taskrs/issues/23

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
